import { IJobRole } from "@/types/job";

export const defaultJobRoles: Array<Omit<IJobRole, "_id" | "id">> = [
  {
    title: "Senior Full-Stack Engineer (Next.js & Node.js)",
    slug: "fullstack-lead",
    department: "Software Engineering",
    category: "engineering",
    location: "Indore HQ / Hybrid",
    experience: "3 - 6 Years",
    type: "Full-Time",
    description:
      "Architect and build high-concurrency web applications, micro-frontends, and mission-critical APIs for global enterprise clients and fast-growing startups.",
    skills: [
      "Next.js 15",
      "TypeScript",
      "React",
      "Node.js",
      "MongoDB / PostgreSQL",
      "Redis",
      "Tailwind CSS",
    ],
    responsibilities: [
      "Lead technical design and development of end-to-end web architectures.",
      "Write clean, modular, and well-tested TypeScript code with high test coverage.",
      "Collaborate with UI/UX designers to implement pixel-perfect, responsive interfaces.",
      "Mentor junior developers and participate in code reviews to maintain high quality.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 1,
  },
  {
    title: "Backend & Cloud Systems Architect",
    slug: "cloud-architect",
    department: "Cloud & Infrastructure",
    category: "cloud",
    location: "Indore HQ / Hybrid",
    experience: "4 - 8 Years",
    type: "Full-Time",
    description:
      "Design fault-tolerant cloud backends, event-driven microservices, and automated CI/CD pipelines capable of handling millions of daily active events.",
    skills: [
      "AWS / GCP",
      "Docker",
      "Kubernetes",
      "Node.js / Python",
      "Kafka / SQS",
      "Terraform",
      "Zero-Trust Security",
    ],
    responsibilities: [
      "Design scalable microservices infrastructure with zero single point of failure.",
      "Automate multi-stage deployments with GitHub Actions and Terraform scripts.",
      "Implement bank-grade data encryption, OWASP hardening, and audit logging.",
      "Optimize database queries, indexing strategies, and caching tiers.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 2,
  },
  {
    title: "Senior Mobile Application Engineer (React Native / Flutter)",
    slug: "mobile-engineer",
    department: "Mobile Engineering",
    category: "engineering",
    location: "Indore HQ / Hybrid",
    experience: "2 - 5 Years",
    type: "Full-Time",
    description:
      "Deliver fluid 60fps cross-platform mobile experiences with offline-first caching, real-time WebSockets, and seamless hardware sensor integration.",
    skills: [
      "React Native",
      "Flutter",
      "TypeScript",
      "Dart",
      "Redux / Zustand",
      "Push Notifications",
      "App Store / Play Console",
    ],
    responsibilities: [
      "Build silky-smooth mobile experiences for iOS and Android.",
      "Integrate complex device sensors, biometric auth, camera streaming, and local storage.",
      "Manage release pipelines, code signing, and App Store / Google Play submissions.",
      "Optimize app bundle sizes and startup performance for low-bandwidth environments.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 3,
  },
  {
    title: "Lead UI/UX & Product Designer",
    slug: "product-designer",
    department: "Design & Creative",
    category: "design",
    location: "Indore HQ / Hybrid",
    experience: "3 - 6 Years",
    type: "Full-Time",
    description:
      "Transform complex business workflows into breathtaking, human-centric user experiences, bespoke design systems, and hyper-interactive prototypes.",
    skills: [
      "Figma",
      "Design Systems",
      "Prototyping",
      "Micro-animations",
      "User Research",
      "Wireframing",
    ],
    responsibilities: [
      "Create enterprise-grade design systems with comprehensive token libraries.",
      "Craft high-fidelity wireframes, interactive prototypes, and usability testing rounds.",
      "Work closely with front-end engineers to ensure 100% design fidelity in production.",
      "Conduct user research interviews and translate feedback into intuitive design patterns.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 4,
  },
  {
    title: "Applied AI & LLM Systems Engineer",
    slug: "ai-engineer",
    department: "Artificial Intelligence",
    category: "ai",
    location: "Indore HQ / Hybrid",
    experience: "2 - 5 Years",
    type: "Full-Time",
    description:
      "Harness state-of-the-art LLMs, vector search, and agentic workflows to build production-grade intelligent systems and automation agents.",
    skills: [
      "Python",
      "OpenAI / Claude APIs",
      "LangChain / LlamaIndex",
      "Vector DBs (Pinecone, pgvector)",
      "RAG Pipelines",
      "FastAPI",
    ],
    responsibilities: [
      "Build high-accuracy RAG (Retrieval-Augmented Generation) pipelines for enterprise data.",
      "Deploy self-hosted open models, embeddings, and fine-tuning pipelines.",
      "Evaluate hallucination rates, token economics, and LLM safety guardrails.",
      "Integrate intelligent AI workflows into web and mobile client applications.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 5,
  },
  {
    title: "DevOps & SRE Engineer",
    slug: "devops-engineer",
    department: "Cloud & Infrastructure",
    category: "cloud",
    location: "Indore HQ / Hybrid",
    experience: "2 - 5 Years",
    type: "Full-Time",
    description:
      "Maintain 99.99% uptime for high-traffic applications through robust monitoring, automated self-healing clusters, and resilient security policies.",
    skills: [
      "Linux",
      "Docker",
      "Kubernetes",
      "Prometheus / Grafana",
      "GitHub Actions",
      "AWS / DigitalOcean",
      "Nginx",
    ],
    responsibilities: [
      "Maintain infrastructure monitoring, uptime dashboards, and real-time incident alerting.",
      "Construct automated rollback pipelines and blue-green zero-downtime releases.",
      "Enforce network firewalls, VPC peering, SSL certificates, and security patches.",
      "Optimize cloud server costs and resource utilization without sacrificing speed.",
    ],
    linkedinUrl: "https://www.linkedin.com/company/appsica/",
    isActive: true,
    order: 6,
  },
];
